### PR TITLE
Update wording and sentence structure - works now better.

### PR DESCRIPTION
**Pull request by econaut6**

### CODE REVIEW

**Review by polux0 — COMMENTED** [review]
Hey Akseli, thanks for creating pull request! Is button on line 84 removed by mistake, or it was on purpose?

**Comment by econaut6** [comment]
must be mistake (tried to take nothing away; just suggesting changes)

**Comment by econaut6** [comment]
yes it was, sorry (now checked), was editing only line 51

**Comment by polux0** [comment]
Closing this request, as proposed changes are being incorporated with other changes on branch `text-changes-1`

**Pull request closed without merging**
